name: Release to Dockerhub
on:
  push:
    paths-ignore:
      - '**.md'
#  pull_request:
#    types:
#      - closed
#    branches: [master, dev]
#    paths-ignore:
#      - '**.md'
#      - '.github/ISSUE_TEMPLATE'
#      - '.gitignore'
#      - 'provisioning'
#      - '.sonarcloud.properties'
#      - 'LICENSE'
#      - 'Vagrantfile'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Maven with Docker Profile and Generate SBOM
        run: mvn clean install -Pdocker -DskipTests -B -DexcludeTestProject=true cyclonedx:makeBom
      - name: Upload WAR File
        uses: actions/upload-artifact@v3
        with:
          name: security_shepherd_war
          path: target/*.war
      - name: Docker Compose Build
        run: docker-compose build
      - name: Generate Tomcat Docker Image SBOM
        uses: anchore/sbom-action@v0
        id: tomcat
        with:
          format: cyclonedx-json
          image: owasp/security-shepherd
          output-file: target/
      - name: Generate MariaDB Docker Image SBOM
        uses: anchore/sbom-action@v0
        id: mariadb
        with:
          format: cyclonedx-json
          image: owasp/security-shepherd_mariadb
          output-file: target/
      - name: Generate MongoDB Docker Image SBOM
        uses: anchore/sbom-action@v0
        id: mongodb
        with:
          format: cyclonedx-json
          image: owasp/security-shepherd_mongo
          output-file: target/
      - name: Upload SBOMs
        uses: actions/upload-artifact@v3
        with:
          name: security_shepherd_sboms
          path: |
            target/*.json
            target/*.xml
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          key: maven-output-${{ hashFiles('target/**') }}
          path: |
            target/
            docker/mariadb/target
            docker/mongo/target

  release-web-app:
    needs: build
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ismisepaul/security-shepherd

      - name: Restore Cached Maven packages
        uses: actions/cache@v3
        with:
          key: maven-output-${{ hashFiles('target/**') }}
          path: |
            target/
            docker/mariadb/target
            docker/mongo/target

      # Dump the environment variables from the dotenv file so they can be used to build the tomcat server
      - name: Set environment variables
        uses: c-py/action-dotenv-to-setenv@80f488cda311f44d43e687a4e94f54a050b7822a  # v4
        with:
          env-file: .env

      - name: Build and push Tomcat
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TOMCAT_DOCKER_VERSION
            TLS_KEYSTORE_FILE
            TLS_KEYSTORE_PASS
            ALIAS
            HTTPS_PORT

  release-database:
    needs: build
    #    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ismisepaul/security-shepherd_mariadb

      - name: Restore Cached Maven packages
        uses: actions/cache@v3
        with:
          key: maven-output-${{ hashFiles('target/**') }}
          path: |
            target/
            docker/mariadb/target
            docker/mongo/target

      - name: Set environment variables
        uses: c-py/action-dotenv-to-setenv@80f488cda311f44d43e687a4e94f54a050b7822a  # v4
        with:
          env-file: .env

      - name: Build and push MariaDb
        uses: docker/build-push-action@v2
        with:
          context: docker/mariadb/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DB_VERSION
            DB_BIND_ADDRESS

  release-mongodb:
    needs: build
    #    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ismisepaul/security-shepherd_mongodb

      - name: Restore Cached Maven packages
        uses: actions/cache@v3
        with:
          key: maven-output-${{ hashFiles('target/**') }}
          path: |
            target/
            docker/mariadb/target
            docker/mongo/target

      - name: Set environment variables
        uses: c-py/action-dotenv-to-setenv@80f488cda311f44d43e687a4e94f54a050b7822a  # v4
        with:
          env-file: .env

      - name: Build and push MongoDb
        uses: docker/build-push-action@v2
        with:
          context: docker/mongo/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MONGODB_VERSION
            MONGO_BIND_ADDRESS


